<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="nl">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title>ZFBootstrap</title>
  		<link rel="stylesheet" href="/css/screen.css" type="text/css" media="screen, projection" /> 
		<link rel="stylesheet" href="/css/print.css" type="text/css" media="print" /> 
		<!--[if lt IE 8]><link rel="stylesheet" href="/css/ie.css" type="text/css" media="screen, projection" /><![endif]-->  		
	</head>
	<body>
		<div class="container showgrid">
			<div class="header">
				This is the header
			</div>